# Configuración de Fly.io para Dashboard Genius
# app se define/edita automáticamente al correr `flyctl launch`

app = "dashboard-genius"
primary_region = "iad"

[build]

[env]
  PORT = "3000"
  NODE_OPTIONS = "--max-old-space-size=896"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "1024mb"
